#!/usr/bin/env python3
import sqlite3
from pathlib import Path


BASE_DIR = Path(__file__).resolve().parent
DB_PATH = BASE_DIR / "game.db"


CARDS = [
    {
        "slug": "twig_forager",
        "name": "Twig Forager",
        "description": "Harvests wood each turn. Best in the Forest Shelf.",
        "card_type": "minion",
        "rarity": "common",
        "school": "Lumber",
        "cost": 1,
        "attack": 1,
        "health": 2,
        "effect_on_play": "",
        "effect_value": 0,
        "keywords": "gather",
        "habitat": "forest",
        "wood_yield": 2,
        "stone_yield": 0,
        "water_yield": 0,
        "palette_start": "#f7e3b1",
        "palette_end": "#b67d45",
        "accent": "#fff4da",
        "starter_copies": 2,
    },
    {
        "slug": "pond_pup",
        "name": "Pond Pup",
        "description": "A young swimmer that stabilizes River turns.",
        "card_type": "minion",
        "rarity": "common",
        "school": "River",
        "cost": 1,
        "attack": 1,
        "health": 3,
        "effect_on_play": "",
        "effect_value": 0,
        "keywords": "river",
        "habitat": "river",
        "wood_yield": 0,
        "stone_yield": 0,
        "water_yield": 1,
        "palette_start": "#a7dcff",
        "palette_end": "#4d87e0",
        "accent": "#dff2ff",
        "starter_copies": 2,
    },
    {
        "slug": "mud_patrol",
        "name": "Mud Patrol",
        "description": "Collects stone and mud for dam work.",
        "card_type": "minion",
        "rarity": "common",
        "school": "Masonry",
        "cost": 1,
        "attack": 2,
        "health": 1,
        "effect_on_play": "",
        "effect_value": 0,
        "keywords": "gather",
        "habitat": "dam",
        "wood_yield": 0,
        "stone_yield": 1,
        "water_yield": 0,
        "palette_start": "#d7c7ad",
        "palette_end": "#7d6850",
        "accent": "#f3e9d7",
        "starter_copies": 2,
    },
    {
        "slug": "canal_scout",
        "name": "Canal Scout",
        "description": "Battlecry: Deal 1 damage to the enemy hero.",
        "card_type": "minion",
        "rarity": "common",
        "school": "River",
        "cost": 2,
        "attack": 2,
        "health": 2,
        "effect_on_play": "damage_enemy_hero",
        "effect_value": 1,
        "keywords": "battlecry",
        "habitat": "river",
        "wood_yield": 1,
        "stone_yield": 0,
        "water_yield": 1,
        "palette_start": "#b6f2ff",
        "palette_end": "#3f9bc9",
        "accent": "#e6fbff",
        "starter_copies": 2,
    },
    {
        "slug": "river_medic",
        "name": "River Medic",
        "description": "Battlecry: Restore 1 Health to your hero.",
        "card_type": "minion",
        "rarity": "common",
        "school": "Watercraft",
        "cost": 2,
        "attack": 2,
        "health": 3,
        "effect_on_play": "heal_friendly_hero",
        "effect_value": 1,
        "keywords": "battlecry,heal",
        "habitat": "river",
        "wood_yield": 0,
        "stone_yield": 0,
        "water_yield": 1,
        "palette_start": "#c4eeff",
        "palette_end": "#4d7fd8",
        "accent": "#e8f7ff",
        "starter_copies": 2,
    },
    {
        "slug": "log_hauler",
        "name": "Log Hauler",
        "description": "Fast worker with heavy wood output.",
        "card_type": "minion",
        "rarity": "common",
        "school": "Lumber",
        "cost": 2,
        "attack": 3,
        "health": 2,
        "effect_on_play": "",
        "effect_value": 0,
        "keywords": "gather",
        "habitat": "forest",
        "wood_yield": 2,
        "stone_yield": 0,
        "water_yield": 0,
        "palette_start": "#ffd9a3",
        "palette_end": "#ba6f3a",
        "accent": "#ffeed2",
        "starter_copies": 2,
    },
    {
        "slug": "splash_restoration",
        "name": "Splash Restoration",
        "description": "Restore 4 Health to your hero.",
        "card_type": "spell",
        "rarity": "common",
        "school": "Wetland",
        "cost": 2,
        "attack": 0,
        "health": 0,
        "effect_on_play": "heal_friendly_hero",
        "effect_value": 4,
        "keywords": "heal",
        "habitat": "any",
        "wood_yield": 0,
        "stone_yield": 0,
        "water_yield": 0,
        "palette_start": "#c8f8ff",
        "palette_end": "#5cc4bc",
        "accent": "#e7feff",
        "starter_copies": 2,
    },
    {
        "slug": "log_toss",
        "name": "Log Toss",
        "description": "Deal 3 damage to the enemy hero.",
        "card_type": "spell",
        "rarity": "common",
        "school": "Lumber",
        "cost": 2,
        "attack": 0,
        "health": 0,
        "effect_on_play": "damage_enemy_hero",
        "effect_value": 3,
        "keywords": "burn",
        "habitat": "any",
        "wood_yield": 0,
        "stone_yield": 0,
        "water_yield": 0,
        "palette_start": "#ffd8a8",
        "palette_end": "#d7623e",
        "accent": "#ffeed8",
        "starter_copies": 2,
    },
    {
        "slug": "dam_patch",
        "name": "Dam Patch",
        "description": "Give a random friendly minion +2/+2.",
        "card_type": "spell",
        "rarity": "rare",
        "school": "Masonry",
        "cost": 1,
        "attack": 0,
        "health": 0,
        "effect_on_play": "buff_random_friendly_minion",
        "effect_value": 2,
        "keywords": "buff",
        "habitat": "any",
        "wood_yield": 0,
        "stone_yield": 0,
        "water_yield": 0,
        "palette_start": "#ead7b4",
        "palette_end": "#9a754d",
        "accent": "#f6eddc",
        "starter_copies": 2,
    },
    {
        "slug": "reed_cartographer",
        "name": "Reed Cartographer",
        "description": "Battlecry: Draw 1 card.",
        "card_type": "minion",
        "rarity": "rare",
        "school": "Survey",
        "cost": 3,
        "attack": 3,
        "health": 3,
        "effect_on_play": "draw_cards",
        "effect_value": 1,
        "keywords": "battlecry,draw",
        "habitat": "river",
        "wood_yield": 0,
        "stone_yield": 0,
        "water_yield": 1,
        "palette_start": "#c6f4ff",
        "palette_end": "#4e89c0",
        "accent": "#ebfcff",
        "starter_copies": 2,
    },
    {
        "slug": "lodge_guard",
        "name": "Lodge Guard",
        "description": "A sturdy defender of the main lodge.",
        "card_type": "minion",
        "rarity": "common",
        "school": "Masonry",
        "cost": 3,
        "attack": 2,
        "health": 5,
        "effect_on_play": "",
        "effect_value": 0,
        "keywords": "defender",
        "habitat": "dam",
        "wood_yield": 0,
        "stone_yield": 2,
        "water_yield": 0,
        "palette_start": "#d9ccb8",
        "palette_end": "#7a6144",
        "accent": "#f0e6d8",
        "starter_copies": 2,
    },
    {
        "slug": "bark_armor",
        "name": "Bark Armor",
        "description": "Give a random friendly minion +3/+3.",
        "card_type": "spell",
        "rarity": "rare",
        "school": "Lumber",
        "cost": 3,
        "attack": 0,
        "health": 0,
        "effect_on_play": "buff_random_friendly_minion",
        "effect_value": 3,
        "keywords": "buff",
        "habitat": "any",
        "wood_yield": 0,
        "stone_yield": 0,
        "water_yield": 0,
        "palette_start": "#e7cf9b",
        "palette_end": "#9a6532",
        "accent": "#f9eed0",
        "starter_copies": 1,
    },
    {
        "slug": "branch_barrage",
        "name": "Branch Barrage",
        "description": "Deal 2 damage to all enemy minions.",
        "card_type": "spell",
        "rarity": "rare",
        "school": "Lumber",
        "cost": 4,
        "attack": 0,
        "health": 0,
        "effect_on_play": "damage_all_enemy_minions",
        "effect_value": 2,
        "keywords": "aoe",
        "habitat": "any",
        "wood_yield": 0,
        "stone_yield": 0,
        "water_yield": 0,
        "palette_start": "#ffc785",
        "palette_end": "#d65f45",
        "accent": "#ffe5bc",
        "starter_copies": 1,
    },
    {
        "slug": "wetland_call",
        "name": "Wetland Call",
        "description": "Summon two 1/1 Builder Kits.",
        "card_type": "spell",
        "rarity": "rare",
        "school": "Wetland",
        "cost": 4,
        "attack": 0,
        "health": 0,
        "effect_on_play": "summon_wisp",
        "effect_value": 2,
        "keywords": "summon",
        "habitat": "any",
        "wood_yield": 0,
        "stone_yield": 0,
        "water_yield": 0,
        "palette_start": "#c1ffd2",
        "palette_end": "#46a774",
        "accent": "#e4ffec",
        "starter_copies": 1,
    },
    {
        "slug": "floodgate_engineer",
        "name": "Floodgate Engineer",
        "description": "Battlecry: Deal 1 damage to the enemy hero.",
        "card_type": "minion",
        "rarity": "rare",
        "school": "Hydraulics",
        "cost": 4,
        "attack": 4,
        "health": 3,
        "effect_on_play": "damage_enemy_hero",
        "effect_value": 1,
        "keywords": "battlecry",
        "habitat": "river",
        "wood_yield": 0,
        "stone_yield": 1,
        "water_yield": 2,
        "palette_start": "#bde4ff",
        "palette_end": "#3761c9",
        "accent": "#e4f3ff",
        "starter_copies": 0,
    },
    {
        "slug": "quarry_forebeaver",
        "name": "Quarry Forebeaver",
        "description": "Massive worker with heavy stone gain.",
        "card_type": "minion",
        "rarity": "rare",
        "school": "Masonry",
        "cost": 4,
        "attack": 3,
        "health": 6,
        "effect_on_play": "",
        "effect_value": 0,
        "keywords": "gather",
        "habitat": "dam",
        "wood_yield": 0,
        "stone_yield": 3,
        "water_yield": 0,
        "palette_start": "#e4d2bd",
        "palette_end": "#7f5d3e",
        "accent": "#f6ebde",
        "starter_copies": 0,
    },
    {
        "slug": "master_damwright",
        "name": "Master Damwright",
        "description": "An elite builder who locks down the Dam shelf.",
        "card_type": "minion",
        "rarity": "epic",
        "school": "Masonry",
        "cost": 5,
        "attack": 4,
        "health": 6,
        "effect_on_play": "",
        "effect_value": 0,
        "keywords": "elite",
        "habitat": "dam",
        "wood_yield": 1,
        "stone_yield": 2,
        "water_yield": 0,
        "palette_start": "#f0ddc0",
        "palette_end": "#9e7043",
        "accent": "#fff1dc",
        "starter_copies": 1,
    },
    {
        "slug": "tail_slap",
        "name": "Tail Slap",
        "description": "Deal 4 damage to a random enemy minion.",
        "card_type": "spell",
        "rarity": "rare",
        "school": "Strike",
        "cost": 3,
        "attack": 0,
        "health": 0,
        "effect_on_play": "damage_random_enemy_minion",
        "effect_value": 4,
        "keywords": "removal",
        "habitat": "any",
        "wood_yield": 0,
        "stone_yield": 0,
        "water_yield": 0,
        "palette_start": "#d3c2ff",
        "palette_end": "#7347be",
        "accent": "#ece0ff",
        "starter_copies": 0,
    },
    {
        "slug": "moonlit_wetlands",
        "name": "Moonlit Wetlands",
        "description": "Draw 2 cards.",
        "card_type": "spell",
        "rarity": "common",
        "school": "Wetland",
        "cost": 2,
        "attack": 0,
        "health": 0,
        "effect_on_play": "draw_cards",
        "effect_value": 2,
        "keywords": "draw",
        "habitat": "any",
        "wood_yield": 0,
        "stone_yield": 0,
        "water_yield": 0,
        "palette_start": "#d6efff",
        "palette_end": "#6494e0",
        "accent": "#ecf7ff",
        "starter_copies": 0,
    },
    {
        "slug": "alder_colossus",
        "name": "Alder Colossus",
        "description": "Huge late-game lumber titan.",
        "card_type": "minion",
        "rarity": "epic",
        "school": "Lumber",
        "cost": 6,
        "attack": 5,
        "health": 7,
        "effect_on_play": "",
        "effect_value": 0,
        "keywords": "colossus",
        "habitat": "forest",
        "wood_yield": 2,
        "stone_yield": 0,
        "water_yield": 0,
        "palette_start": "#ffe0ac",
        "palette_end": "#a15c2f",
        "accent": "#fff0d3",
        "starter_copies": 0,
    },
    {
        "slug": "torrent_release",
        "name": "Torrent Release",
        "description": "Deal 4 damage to all enemy minions.",
        "card_type": "spell",
        "rarity": "epic",
        "school": "Hydraulics",
        "cost": 6,
        "attack": 0,
        "health": 0,
        "effect_on_play": "damage_all_enemy_minions",
        "effect_value": 4,
        "keywords": "aoe",
        "habitat": "any",
        "wood_yield": 0,
        "stone_yield": 0,
        "water_yield": 0,
        "palette_start": "#c8e5ff",
        "palette_end": "#3f63cf",
        "accent": "#e6f2ff",
        "starter_copies": 0,
    },
    {
        "slug": "great_lodge_elder",
        "name": "Great Lodge Elder",
        "description": "Battlecry: Restore 3 Health to your hero.",
        "card_type": "minion",
        "rarity": "epic",
        "school": "Elder",
        "cost": 6,
        "attack": 6,
        "health": 6,
        "effect_on_play": "heal_friendly_hero",
        "effect_value": 3,
        "keywords": "battlecry,heal",
        "habitat": "dam",
        "wood_yield": 0,
        "stone_yield": 1,
        "water_yield": 2,
        "palette_start": "#f5dcbf",
        "palette_end": "#936542",
        "accent": "#ffefdb",
        "starter_copies": 0,
    },
    {
        "slug": "night_shift_builder",
        "name": "Night Shift Builder",
        "description": "Battlecry: Draw 1 card.",
        "card_type": "minion",
        "rarity": "rare",
        "school": "Lodgecraft",
        "cost": 4,
        "attack": 4,
        "health": 4,
        "effect_on_play": "draw_cards",
        "effect_value": 1,
        "keywords": "battlecry,draw",
        "habitat": "dam",
        "wood_yield": 1,
        "stone_yield": 1,
        "water_yield": 0,
        "palette_start": "#efd5b7",
        "palette_end": "#7f5337",
        "accent": "#faead6",
        "starter_copies": 0,
    },
    {
        "slug": "iron_tooth_matriarch",
        "name": "Iron-Tooth Matriarch",
        "description": "Final-boss beaver of the Great Dam.",
        "card_type": "minion",
        "rarity": "legendary",
        "school": "Sovereign",
        "cost": 7,
        "attack": 8,
        "health": 8,
        "effect_on_play": "",
        "effect_value": 0,
        "keywords": "legendary",
        "habitat": "dam",
        "wood_yield": 1,
        "stone_yield": 2,
        "water_yield": 1,
        "palette_start": "#ffdeb1",
        "palette_end": "#8e4f2d",
        "accent": "#fff0d5",
        "starter_copies": 0,
    },
    {
        "slug": "boulder_bastion",
        "name": "Boulder Bastion",
        "description": "Guard. Enemy attacks must target this first.",
        "card_type": "minion",
        "rarity": "rare",
        "school": "Masonry",
        "cost": 3,
        "attack": 2,
        "health": 6,
        "effect_on_play": "",
        "effect_value": 0,
        "keywords": "guard",
        "habitat": "dam",
        "wood_yield": 0,
        "stone_yield": 2,
        "water_yield": 0,
        "palette_start": "#e7dccb",
        "palette_end": "#8d765d",
        "accent": "#f6f0e5",
        "starter_copies": 1,
    },
    {
        "slug": "swift_current_raider",
        "name": "Swift Current Raider",
        "description": "Fury. Can attack twice each turn.",
        "card_type": "minion",
        "rarity": "rare",
        "school": "River",
        "cost": 4,
        "attack": 3,
        "health": 3,
        "effect_on_play": "",
        "effect_value": 0,
        "keywords": "fury",
        "habitat": "river",
        "wood_yield": 0,
        "stone_yield": 0,
        "water_yield": 2,
        "palette_start": "#cceaff",
        "palette_end": "#4b87cb",
        "accent": "#ecf7ff",
        "starter_copies": 1,
    },
    {
        "slug": "sawtooth_hunter",
        "name": "Sawtooth Hunter",
        "description": "Poisonous. Any damage from this destroys minions.",
        "card_type": "minion",
        "rarity": "rare",
        "school": "Wilds",
        "cost": 3,
        "attack": 1,
        "health": 2,
        "effect_on_play": "",
        "effect_value": 0,
        "keywords": "poisonous",
        "habitat": "forest",
        "wood_yield": 1,
        "stone_yield": 0,
        "water_yield": 0,
        "palette_start": "#d9ffb8",
        "palette_end": "#5a9f46",
        "accent": "#ecffd9",
        "starter_copies": 0,
    },
    {
        "slug": "marsh_reclaimer",
        "name": "Marsh Reclaimer",
        "description": "Lifesteal.",
        "card_type": "minion",
        "rarity": "epic",
        "school": "Wetland",
        "cost": 5,
        "attack": 4,
        "health": 5,
        "effect_on_play": "",
        "effect_value": 0,
        "keywords": "lifesteal",
        "habitat": "river",
        "wood_yield": 0,
        "stone_yield": 0,
        "water_yield": 1,
        "palette_start": "#ffd3e1",
        "palette_end": "#a54e72",
        "accent": "#ffe8f0",
        "starter_copies": 1,
    },
]


LEVELS = [
    {
        "id": 1,
        "name": "Level 1: Creekside Lessons",
        "subtitle": "Learn resource gathering and lane habitats.",
        "enemy_hero": "Nibble Swifttail",
        "enemy_health": 24,
        "ai_difficulty": 1,
        "intro": "Creek workers flood the board with basic gatherers. Practice efficient trades.",
        "card_back_start": "#bde4ff",
        "card_back_end": "#55a7e3",
    },
    {
        "id": 2,
        "name": "Level 2: Timber Rush",
        "subtitle": "Fast wood generation and sudden pressure.",
        "enemy_hero": "Foreman Oakbite",
        "enemy_health": 28,
        "ai_difficulty": 2,
        "intro": "Oakbite snowballs in the Forest Shelf. Deny his early lumber engines.",
        "card_back_start": "#ffd9a6",
        "card_back_end": "#c67a42",
    },
    {
        "id": 3,
        "name": "Level 3: Mudwall Stand",
        "subtitle": "Defensive Dam lane play with buffs.",
        "enemy_hero": "Warden Claytail",
        "enemy_health": 32,
        "ai_difficulty": 3,
        "intro": "Claytail fortifies the dam and makes trades awkward. Save removal for anchors.",
        "card_back_start": "#e8d2b7",
        "card_back_end": "#8a6747",
    },
    {
        "id": 4,
        "name": "Level 4: Flood Season",
        "subtitle": "Hydraulic spells and wave-based tempo.",
        "enemy_hero": "Hydra Sluicepaw",
        "enemy_health": 36,
        "ai_difficulty": 4,
        "intro": "Sluicepaw weaponizes water surges. Keep board width controlled.",
        "card_back_start": "#cdeaff",
        "card_back_end": "#3f68ca",
    },
    {
        "id": 5,
        "name": "Level 5: Elder Lodge",
        "subtitle": "Long-game value and late stabilizers.",
        "enemy_hero": "Elder Broadtail",
        "enemy_health": 40,
        "ai_difficulty": 5,
        "intro": "Broadtail excels in attrition. Close before the elder engines outscale you.",
        "card_back_start": "#f1d7b6",
        "card_back_end": "#8b5b3d",
    },
    {
        "id": 6,
        "name": "Level 6: Great Dam Sovereign",
        "subtitle": "Final trial of full-spectrum beaver strategy.",
        "enemy_hero": "Matriarch Iron-Tooth",
        "enemy_health": 44,
        "ai_difficulty": 6,
        "intro": "The sovereign combines gather, burst, and heavy board control. Build the perfect dam.",
        "card_back_start": "#ffe1b9",
        "card_back_end": "#9a4f31",
    },
    {
        "id": 7,
        "name": "Level 7: Rampart Rebellion",
        "subtitle": "Guard lines and grinding board pressure.",
        "enemy_hero": "Commander Stonehide",
        "enemy_health": 48,
        "ai_difficulty": 7,
        "intro": "Stonehide fortifies with Guard walls before striking back with elite units.",
        "card_back_start": "#e5dccf",
        "card_back_end": "#786857",
    },
    {
        "id": 8,
        "name": "Level 8: Rapids Ambush",
        "subtitle": "Fury chains and relentless tempo swings.",
        "enemy_hero": "Racer Swiftwake",
        "enemy_health": 52,
        "ai_difficulty": 8,
        "intro": "Swiftwake attacks in rapid bursts. If you lose board once, the game snowballs fast.",
        "card_back_start": "#d1ecff",
        "card_back_end": "#3f77bd",
    },
    {
        "id": 9,
        "name": "Level 9: Moonfall Citadel",
        "subtitle": "Final gauntlet of poison, lifesteal, and heavy control.",
        "enemy_hero": "High Regent Moonclaw",
        "enemy_health": 58,
        "ai_difficulty": 9,
        "intro": "Moonclaw combines every advanced tactic. Survive the attrition and finish cleanly.",
        "card_back_start": "#f6d9ff",
        "card_back_end": "#6a3d99",
    },
]


LEVEL_DECKS = {
    1: {
        "twig_forager": 2,
        "pond_pup": 2,
        "mud_patrol": 2,
        "canal_scout": 2,
        "river_medic": 2,
        "log_hauler": 2,
        "splash_restoration": 2,
        "log_toss": 2,
        "dam_patch": 2,
        "reed_cartographer": 2,
    },
    2: {
        "twig_forager": 2,
        "log_hauler": 2,
        "canal_scout": 2,
        "dam_patch": 2,
        "lodge_guard": 2,
        "reed_cartographer": 2,
        "bark_armor": 2,
        "branch_barrage": 2,
        "moonlit_wetlands": 2,
        "log_toss": 2,
    },
    3: {
        "mud_patrol": 2,
        "lodge_guard": 2,
        "bark_armor": 2,
        "wetland_call": 2,
        "reed_cartographer": 2,
        "master_damwright": 2,
        "quarry_forebeaver": 2,
        "splash_restoration": 2,
        "tail_slap": 2,
        "log_toss": 2,
    },
    4: {
        "pond_pup": 2,
        "canal_scout": 2,
        "floodgate_engineer": 2,
        "moonlit_wetlands": 2,
        "tail_slap": 2,
        "branch_barrage": 2,
        "wetland_call": 2,
        "master_damwright": 2,
        "torrent_release": 2,
        "night_shift_builder": 2,
    },
    5: {
        "quarry_forebeaver": 2,
        "master_damwright": 2,
        "night_shift_builder": 2,
        "great_lodge_elder": 2,
        "alder_colossus": 2,
        "tail_slap": 2,
        "torrent_release": 2,
        "branch_barrage": 2,
        "moonlit_wetlands": 2,
        "wetland_call": 2,
    },
    6: {
        "twig_forager": 1,
        "canal_scout": 2,
        "river_medic": 2,
        "log_toss": 2,
        "dam_patch": 2,
        "floodgate_engineer": 2,
        "quarry_forebeaver": 2,
        "night_shift_builder": 2,
        "torrent_release": 2,
        "great_lodge_elder": 2,
        "iron_tooth_matriarch": 1,
    },
    7: {
        "boulder_bastion": 2,
        "lodge_guard": 2,
        "quarry_forebeaver": 2,
        "master_damwright": 2,
        "dam_patch": 2,
        "tail_slap": 2,
        "branch_barrage": 2,
        "night_shift_builder": 2,
        "great_lodge_elder": 2,
        "alder_colossus": 2,
    },
    8: {
        "swift_current_raider": 2,
        "canal_scout": 2,
        "floodgate_engineer": 2,
        "moonlit_wetlands": 2,
        "log_toss": 2,
        "tail_slap": 2,
        "branch_barrage": 2,
        "wetland_call": 2,
        "marsh_reclaimer": 2,
        "torrent_release": 2,
    },
    9: {
        "boulder_bastion": 2,
        "swift_current_raider": 2,
        "sawtooth_hunter": 2,
        "marsh_reclaimer": 2,
        "dam_patch": 2,
        "tail_slap": 2,
        "branch_barrage": 2,
        "torrent_release": 2,
        "great_lodge_elder": 2,
        "iron_tooth_matriarch": 2,
    },
}


def initialize_db(db_path: Path = DB_PATH) -> None:
    if db_path.exists():
        db_path.unlink()

    conn = sqlite3.connect(db_path)
    cur = conn.cursor()

    cur.executescript(
        """
        CREATE TABLE cards (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            slug TEXT NOT NULL UNIQUE,
            name TEXT NOT NULL,
            description TEXT NOT NULL,
            card_type TEXT NOT NULL CHECK (card_type IN ('minion', 'spell')),
            rarity TEXT NOT NULL CHECK (rarity IN ('common', 'rare', 'epic', 'legendary')),
            school TEXT NOT NULL,
            cost INTEGER NOT NULL,
            attack INTEGER NOT NULL DEFAULT 0,
            health INTEGER NOT NULL DEFAULT 0,
            effect_on_play TEXT NOT NULL DEFAULT '',
            effect_value INTEGER NOT NULL DEFAULT 0,
            keywords TEXT NOT NULL DEFAULT '',
            habitat TEXT NOT NULL CHECK (habitat IN ('forest', 'river', 'dam', 'any')),
            wood_yield INTEGER NOT NULL DEFAULT 0,
            stone_yield INTEGER NOT NULL DEFAULT 0,
            water_yield INTEGER NOT NULL DEFAULT 0,
            palette_start TEXT NOT NULL,
            palette_end TEXT NOT NULL,
            accent TEXT NOT NULL,
            starter_copies INTEGER NOT NULL DEFAULT 0
        );

        CREATE TABLE levels (
            id INTEGER PRIMARY KEY,
            name TEXT NOT NULL,
            subtitle TEXT NOT NULL,
            enemy_hero TEXT NOT NULL,
            enemy_health INTEGER NOT NULL,
            ai_difficulty INTEGER NOT NULL,
            intro TEXT NOT NULL,
            card_back_start TEXT NOT NULL,
            card_back_end TEXT NOT NULL
        );

        CREATE TABLE level_decks (
            level_id INTEGER NOT NULL,
            card_id INTEGER NOT NULL,
            copies INTEGER NOT NULL,
            PRIMARY KEY (level_id, card_id),
            FOREIGN KEY (level_id) REFERENCES levels(id),
            FOREIGN KEY (card_id) REFERENCES cards(id)
        );
        """
    )

    cur.executemany(
        """
        INSERT INTO cards (
            slug, name, description, card_type, rarity, school,
            cost, attack, health, effect_on_play, effect_value,
            keywords, habitat, wood_yield, stone_yield, water_yield,
            palette_start, palette_end, accent, starter_copies
        )
        VALUES (
            :slug, :name, :description, :card_type, :rarity, :school,
            :cost, :attack, :health, :effect_on_play, :effect_value,
            :keywords, :habitat, :wood_yield, :stone_yield, :water_yield,
            :palette_start, :palette_end, :accent, :starter_copies
        );
        """,
        CARDS,
    )

    cur.executemany(
        """
        INSERT INTO levels (
            id, name, subtitle, enemy_hero, enemy_health, ai_difficulty,
            intro, card_back_start, card_back_end
        )
        VALUES (
            :id, :name, :subtitle, :enemy_hero, :enemy_health, :ai_difficulty,
            :intro, :card_back_start, :card_back_end
        );
        """,
        LEVELS,
    )

    slug_to_id = {
        slug: card_id for card_id, slug in cur.execute("SELECT id, slug FROM cards").fetchall()
    }

    level_deck_rows = []
    for level_id, entries in LEVEL_DECKS.items():
        for slug, copies in entries.items():
            level_deck_rows.append((level_id, slug_to_id[slug], copies))

    cur.executemany(
        "INSERT INTO level_decks (level_id, card_id, copies) VALUES (?, ?, ?)",
        level_deck_rows,
    )

    conn.commit()
    conn.close()


if __name__ == "__main__":
    initialize_db(DB_PATH)
    print(f"Initialized database at {DB_PATH}")
